# https://doc.rust-lang.org/stable/clippy/lint_configuration.html
# https://rust-lang.github.io/rust-clippy/master/index.html

avoid-breaking-exported-api = false

disallowed-types = [
  { path = "core::ffi::c_char", replacement = "u8", reason = "c_char may be different types on different platforms" },
  { path = "libc::c_char", replacement = "u8", reason = "c_char may be different types on different platforms" },
  { path = "std::ffi::c_char", replacement = "u8", reason = "c_char may be different types on different platforms" },
]
