# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering
name: sarif report

jobs:
  clippy-upload-sarif:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Install system dependencies (ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses-dev libevent-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy
      - run: cargo install clippy-sarif
      - run: cargo clippy --message-format=json -- | clippy-sarif > clippy.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: clippy.sarif
          category: clippy
